name: 'Download a cxx-common'
description: 'Download a specific version of cxx-common artifact'
inputs:
  arch:
    description: 'Target architecture'
    required: true
  llvm:
    description: 'LLVM version'
    required: true
  version:
    description: 'cxx-common version'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
