name: 'Download a cxx-common'
description: 'Download a specific version of cxx-common artifact'
inputs:
  llvm:
    description: 'LLVM version'
    required: true
  version:
    description: 'cxx-common version'
    required: false
    default: latest
  path:
    description: 'Destination path'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
