name: Test the action

on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test action locally
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test download-cxx-common
        # Use the action defined in this repository
        id: cxxcommon
        uses: ./
        with:
          llvm: 13
          version: v0.2.2
          token: ${{ secrets.GITHUB_TOKEN }}
          destination: ./install

      - name: Test paths
        shell: bash
        run: |
          echo ${{ steps.cxxcommon.outputs.path }}

